import type { Inspeccion, NoConformidad, Proyecto, ConfiguracionRolesRevision } from "./types";

export const proyectos: Proyecto[] = [
  {
    id: "p1",
    nombre: "Residencial Los Álamos - Etapa II",
    ubicacion: "Surco, Lima",
    cliente: "Inmobiliaria Andina S.A.C.",
    residente: "Ing. Carlos Mendoza",
  },
  {
    id: "p2",
    nombre: "Edificio Corporativo San Isidro",
    ubicacion: "San Isidro, Lima",
    cliente: "Grupo Constructor Pacífico",
    residente: "Ing. Rosa Huamán",
  },
  {
    id: "p3",
    nombre: "Planta Industrial Lurín",
    ubicacion: "Lurín, Lima",
    cliente: "Industrias del Sur E.I.R.L.",
    residente: "Ing. Jorge Salazar",
  },
];

export const configuracionesRolesRevision: ConfiguracionRolesRevision[] = [
  {
    id: "crr1",
    proyectoId: "p1",
    rolesRevision: ["Producción", "Calidad", "Residente", "Supervisor"],
    requiereTodasLasRevisiones: false,
  },
  {
    id: "crr2",
    proyectoId: "p2",
    rolesRevision: ["Calidad", "Supervisor"],
    requiereTodasLasRevisiones: false,
  },
  {
    id: "crr3",
    proyectoId: "p3",
    rolesRevision: ["Producción", "Calidad", "Residente", "Supervisor", "Subcontratista"],
    requiereTodasLasRevisiones: false,
  },
];

export const inspecciones: Inspeccion[] = [
  {
    id: "i1",
    codigo: "INS-2026-014",
    proyectoId: "p1",
    ubicacion: "Piso 4",
    unidadControl: "Losa",
    protocoloId: "proto-concreto",
    tipo: "Concreto",
    fecha: "2026-09-18",
    inspector: "Ing. Paola Ríos",
    resultado: "Aprobado",
    cumplimiento: 100,
    items: [
      { id: "1", descripcion: "Ensayo de slump dentro de rango (3\"-4\")", respuesta: "cumple", evidencias: [] },
      { id: "2", descripcion: "Probetas tomadas y rotuladas (3 unid.)", respuesta: "cumple", evidencias: [] },
      { id: "3", descripcion: "Encofrado verificado y aprobado", respuesta: "cumple", evidencias: [] },
      { id: "4", descripcion: "Acero de refuerzo según plano estructural", respuesta: "cumple", evidencias: [] },
    ],
    evidenciasGenerales: [],
    participantes: [],
    estado: "Pendiente",
    estadoRevision: "En Revisión",
    registrosRevision: [
      { id: "r1", rol: "Calidad", nombreRevisor: "Ing. Carlos Mendoza", fechaHora: "2026-09-18T14:00:00Z" },
    ],
    finalizada: false,
    tipoRegistro: "checklist",
  },
  {
    id: "i2",
    codigo: "INS-2026-015",
    proyectoId: "p1",
    ubicacion: "Eje 3-4",
    unidadControl: "Columnas",
    protocoloId: "proto-encofrado",
    tipo: "Encofrado",
    fecha: "2026-09-19",
    inspector: "Ing. Paola Ríos",
    resultado: "Falla",
    cumplimiento: 75,
    items: [
      { id: "1", descripcion: "Verticalidad de encofrado (tolerancia ±5mm)", respuesta: "cumple", evidencias: [] },
      {
        id: "2",
        descripcion: "Limpieza interior del encofrado",
        respuesta: "no_cumple",
        comentario: "Restos de aserrín en base de columna C3",
        evidencias: [],
      },
      { id: "3", descripcion: "Aplicación de desmoldante", respuesta: "cumple", evidencias: [] },
      { id: "4", descripcion: "Arriostres y apuntalamiento", respuesta: "cumple", evidencias: [] },
    ],
    evidenciasGenerales: [],
    participantes: [],
    estado: "Pendiente",
    estadoRevision: "En Revisión",
    registrosRevision: [
      { id: "r2", rol: "Producción", nombreRevisor: "Ing. Juan Flores", fechaHora: "2026-09-19T09:00:00Z" },
    ],
    finalizada: false,
    tipoRegistro: "checklist",
  },
  {
    id: "i3",
    codigo: "INS-2026-009",
    proyectoId: "p2",
    ubicacion: "Piso 2",
    unidadControl: "Tablero general",
    protocoloId: "proto-instalaciones",
    tipo: "Instalaciones",
    fecha: "2026-09-10",
    inspector: "Ing. Luis Farfán",
    resultado: "Falla",
    cumplimiento: 40,
    items: [
      {
        id: "1",
        descripcion: "Identificación y rotulado de circuitos",
        respuesta: "no_cumple",
        comentario: "Sin rotulado",
        evidencias: [],
      },
      {
        id: "2",
        descripcion: "Puesta a tierra medida y conforme",
        respuesta: "no_cumple",
        comentario: "Resistencia fuera de norma",
        evidencias: [],
      },
      { id: "3", descripcion: "Prueba de continuidad", respuesta: "cumple", evidencias: [] },
    ],
    evidenciasGenerales: [],
    participantes: [],
    estado: "Pendiente",
    estadoRevision: "Nueva",
    registrosRevision: [],
    finalizada: false,
    tipoRegistro: "checklist",
  },
  {
    id: "i4",
    codigo: "INS-2026-016",
    proyectoId: "p3",
    ubicacion: "Cimentación",
    unidadControl: "Losa",
    protocoloId: "proto-impermeabilizacion",
    tipo: "Impermeabilización",
    fecha: "2026-09-21",
    inspector: "Ing. Jorge Salazar",
    resultado: "Aprobado",
    cumplimiento: 100,
    items: [
      { id: "1", descripcion: "Superficie limpia y seca antes de aplicación", respuesta: "cumple", evidencias: [] },
      { id: "2", descripcion: "Espesor de membrana según especificación", respuesta: "cumple", evidencias: [] },
      { id: "3", descripcion: "Prueba de inundación 24h sin filtraciones", respuesta: "cumple", evidencias: [] },
    ],
    evidenciasGenerales: [],
    participantes: [],
    estado: "Pendiente",
    estadoRevision: "Revisiones Completadas",
    registrosRevision: [
      { id: "r4a", rol: "Producción", nombreRevisor: "Ing. Pedro López", fechaHora: "2026-09-21T09:00:00Z" },
      { id: "r4b", rol: "Calidad", nombreRevisor: "Ing. Rosa Huamán", fechaHora: "2026-09-21T11:00:00Z" },
      { id: "r4c", rol: "Supervisor", nombreRevisor: "Ing. Jorge Salazar", fechaHora: "2026-09-21T13:00:00Z" },
    ],
    finalizada: false,
    tipoRegistro: "checklist",
  },
];

export const noConformidades: NoConformidad[] = [
  {
    id: "nc1",
    codigo: "NC-2026-021",
    proyectoId: "p2",
    ubicacion: "Piso 2",
    unidadControl: "Tablero general",
    descripcion: "Puesta a tierra fuera de norma (resistencia medida 38Ω, máximo permitido 25Ω).",
    severidad: "Crítica",
    estado: "Abierta",
    responsable: "Ing. Luis Farfán",
    fechaApertura: "2026-09-10",
    fechaLimite: "2026-09-24",
    inspeccionOriginId: "i3",
  },
  {
    id: "nc2",
    codigo: "NC-2026-020",
    proyectoId: "p1",
    ubicacion: "Eje 3-4",
    unidadControl: "Columnas",
    descripcion: "Restos de aserrín y material suelto en base de columna C3 previo al vaciado.",
    severidad: "Menor",
    estado: "En proceso",
    responsable: "Ing. Paola Ríos",
    fechaApertura: "2026-09-19",
    fechaLimite: "2026-09-22",
    inspeccionOriginId: "i2",
  },
  {
    id: "nc3",
    codigo: "NC-2026-018",
    proyectoId: "p1",
    ubicacion: "Sector B",
    unidadControl: "Zapatas",
    descripcion: "Recubrimiento de acero menor al especificado en 3 zapatas (25mm medido vs 40mm de diseño).",
    severidad: "Mayor",
    estado: "Cerrada",
    responsable: "Ing. Carlos Mendoza",
    fechaApertura: "2026-09-02",
    fechaLimite: "2026-09-09",
  },
  {
    id: "nc4",
    codigo: "NC-2026-019",
    proyectoId: "p3",
    ubicacion: "Muro perimetral norte",
    unidadControl: "Albañilería",
    descripcion: "Juntas de asentado con espesor variable, fuera de tolerancia (10-15mm vs 10mm especificado).",
    severidad: "Menor",
    estado: "Abierta",
    responsable: "Ing. Jorge Salazar",
    fechaApertura: "2026-09-15",
    fechaLimite: "2026-09-29",
  },
];

export function nombreProyecto(id: string): string {
  return proyectos.find((p) => p.id === id)?.nombre ?? "—";
}
