import type { Usuario } from "./types";

export const usuariosSeed: Usuario[] = [
  {
    id: "u1",
    nombre: "Carlos Mendoza",
    email: "carlos.mendoza@constructoraandina.pe",
    rol: "Residente",
    estado: "Activo",
    fechaCreacion: "2026-06-02",
    proyectoIds: ["p1", "p2", "p3"],
  },
  {
    id: "u2",
    nombre: "Paola Ríos",
    email: "paola.rios@constructoraandina.pe",
    rol: "Calidad",
    estado: "Activo",
    fechaCreacion: "2026-06-02",
    proyectoIds: ["p1", "p2", "p3"],
  },
  {
    id: "u3",
    nombre: "Jorge Salazar",
    email: "jorge.salazar@constructoraandina.pe",
    rol: "Residente",
    estado: "Activo",
    fechaCreacion: "2026-06-10",
    proyectoIds: ["p1", "p2", "p3"],
  },
  {
    id: "u4",
    nombre: "Luis Farfán",
    email: "luis.farfan@constructoraandina.pe",
    rol: "Calidad",
    estado: "Activo",
    fechaCreacion: "2026-06-10",
    proyectoIds: ["p1", "p2", "p3"],
  },
  {
    id: "u5",
    nombre: "Miguel Torres",
    email: "miguel.torres@constructoraandina.pe",
    rol: "Producción",
    estado: "Activo",
    fechaCreacion: "2026-07-01",
    proyectoIds: ["p1", "p2", "p3"],
  },
  {
    id: "u6",
    nombre: "Ana Quispe",
    email: "ana.quispe@constructoraandina.pe",
    rol: "Supervisor",
    estado: "Activo",
    fechaCreacion: "2026-07-01",
    proyectoIds: ["p1", "p2", "p3"],
  },
  {
    id: "u7",
    nombre: "Electro Instalaciones S.R.L.",
    email: "contacto@electroinstalaciones.pe",
    rol: "Subcontratista",
    estado: "Activo",
    fechaCreacion: "2026-08-14",
    proyectoIds: ["p1", "p2", "p3"],
  },
  {
    id: "u8",
    nombre: "Rosa Huamán",
    email: "rosa.huaman@grupopacifico.pe",
    rol: "Visualizador",
    estado: "Inactivo",
    fechaCreacion: "2026-08-20",
    proyectoIds: [],
  },
];
